; Automatically generated by /usr/lib/cumulus/update-ports.
; Wed Jun  8 20:04:39 2022
; Do not edit.


;;;
;;; Constants
;;;

;;;
;;; The link scan base address points to an array of per-port data (32
;;; elements, 2 bytes each) which is continually updated by the main CPU's
;;; linkscan task.
LINKSCAN_P         equ    0x80 ; port data base address

;;; bits in the port data fields
LINKSCAN_LINK      equ    0x0  ; link down/up
LINKSCAN_TX        equ    0x4  ; transmitted packet
LINKSCAN_RX        equ    0x5  ; received packet

;;;
;;; The port status base address points to an array of per-port data (32
;;; elements, 2 bytes each) which is continually updated by the switch chip.
;;; This address is implied by port related op codes
PORTSTATUS_P       equ    0x00 ; port status base address

;;; bits in the linkscan port status fields
PORTSTATUS_RX      equ    0x0  ; received packet
PORTSTATUS_TX      equ    0x1  ; transmitted packet
PORTSTATUS_COLL    equ    0x2  ; collision
PORTSTATUS_SPEED_C equ    0x3  ; 100Mbps
PORTSTATUS_SPEED_M equ    0x4  ; 1Gbps
PORTSTATUS_DUPLEX  equ    0x5  ; half/full duplex
PORTSTATUS_FLOW    equ    0x6  ; flow control capable
PORTSTATUS_LINKUP  equ    0x7  ; link down/up
PORTSTATUS_LINKEN  equ    0x8  ; link disabled/enabled
PORTSTATUS_ZERO    equ    0xe  ; always 0
PORTSTATUS_ONE     equ    0xf  ; always 1

;;;
;;; Blink constants
TICKS_PER_SEC      equ    30   ; LED program runs at 30Hz


;;;
;;; Platform-specific defines
TICKS_PER_BLINK    equ    3    ; 0 to alternate every cycle (15Hz)
NUM_LEDS           equ    72


;;;
;;; Variables
;;;
;;; Addresses 0xa0 to 0xff are initialized to zero and usable by the program.
;;;

;;;
;;; Keep track of blink state, modified each cycle as a timer
BLINK_TICKS_P      equ    0xf0
BLINK_STATE_P      equ    0xf1


main:
        
        ld      a,1
        call    set_led_CelRedstoneXpSFPp
        ld      a,2
        call    set_led_CelRedstoneXpSFPp
        ld      a,3
        call    set_led_CelRedstoneXpSFPp
        ld      a,4
        call    set_led_CelRedstoneXpSFPp
        ld      a,5
        call    set_led_CelRedstoneXpSFPp
        ld      a,6
        call    set_led_CelRedstoneXpSFPp
        ld      a,7
        call    set_led_CelRedstoneXpSFPp
        ld      a,8
        call    set_led_CelRedstoneXpSFPp
        ld      a,9
        call    set_led_CelRedstoneXpSFPp
        ld      a,10
        call    set_led_CelRedstoneXpSFPp
        ld      a,11
        call    set_led_CelRedstoneXpSFPp
        ld      a,12
        call    set_led_CelRedstoneXpSFPp
        ld      a,13
        call    set_led_CelRedstoneXpQSFPp
        ld      a,14
        call    set_led_CelRedstoneXpQSFPp
        ld      a,15
        call    set_led_CelRedstoneXpQSFPp
        ld      a,16
        call    set_led_CelRedstoneXpQSFPp
        ld      a,17
        call    set_led_CelRedstoneXpQSFPp
        ld      a,18
        call    set_led_CelRedstoneXpQSFPp

        call blink_update_state
        send NUM_LEDS


blink_update_state:
        ld      a,(BLINK_TICKS_P)
        cmp     a,0
        jz      blink_toggle
        dec     a
        ld      (BLINK_TICKS_P),a
        ret
blink_toggle:
        ld      a,(BLINK_STATE_P)
        xor     a,0x01
        and     a,0x01
        ld      (BLINK_STATE_P),a
        ld      a,TICKS_PER_BLINK
        ld      (BLINK_TICKS_P),a
        ret


;;; CelRedstoneXpQSFPp
;;;
;;; For 40G mode, we use only the first LED to indicate link/activity.
;;; The other 3 LEDs will be off.
;;;
set_led_CelRedstoneXpQSFPp:
        call    set_any_led    ; set the first led green/off

        push    PORTSTATUS_ONE ; 1, 1 => led 2 off
        pack
        push    PORTSTATUS_ONE
        pack

        push    PORTSTATUS_ONE ; 1, 1 => led 3 off
        pack
        push    PORTSTATUS_ONE
        pack

        push    PORTSTATUS_ONE ; 1, 1 => led 4 off
        pack
        push    PORTSTATUS_ONE
        pack

        ret

;;; CelRedstoneXpSFPp
;;
;;; Each port on the Redstone XP uses two bits (SFP and QSFP), they
;;;  behave as follows:
;;;
;;;                  bit 0
;;;                0        1
;;;            +--------+-------+
;;;          0 | green  |  off  |
;;;   bit 1    +--------+-------+
;;;          1 |  red   |  off  |
;;;            +--------+-------+
set_led_CelRedstoneXpSFPp:
set_any_led:
;;; The first bit will indicate link/activity (low active)
;;; The second bit will always be 0
;;;
        port a

        pushst  PORTSTATUS_RX
        pushst  PORTSTATUS_TX
        tor
        push    (BLINK_STATE_P)
        tand
        tinv                    ; flash off with activity
        pushst  PORTSTATUS_LINKEN
        tand
        tinv
        pack

        port 1
        pushst  PORTSTATUS_ZERO ; disable yellow LED
        pack

        ret


